name: optum_gen_ai_chatbot_template
description: ''
version: '1.5'
author: sumitpaul@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: optumgenaichatbottemplate
  parentArtefactID: sumitpaulprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-10-03 01:38:26'
pipelines:
  pipelines/data_vectorize:
    name: data_vectorize
    description: ''
    author: sumitpaul@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-03 01:38:26'
    datasets:
      inputs:
      - datasets/content_vectorized
      - datasets/optum_pdf
      - datasets/parse_docx
      outputs:
      - datasets/Populate_Vector_DB
    subgraphs: []
    dependencies: {}
  pipelines/chatbot-live:
    name: chatbot-live
    description: ''
    author: sumitpaul@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-10-03 11:28:40'
    datasets:
      inputs:
      - datasets/content_vectorized
      - datasets/get_queries_msk
      outputs:
      - datasets/bot_message
    subgraphs: []
    dependencies: {}
  pipelines/chatbot-opensearch-sagemaker:
    name: chatbot-opensearch-sagemaker
    description: ''
    author: sumitpaul@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-10-11 11:53:25'
    datasets:
      inputs:
      - datasets/content_vectorized
      - datasets/get_queries_msk
      outputs:
      - datasets/bot_message
    subgraphs: []
    dependencies: {}
  pipelines/optum-pdf-data-vectorize:
    name: optum-pdf-data-vectorize
    description: ''
    author: sumitpaul@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-18 14:05:26'
    datasets:
      inputs:
      - datasets/read_pdf
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/gem-builder:
    name: gem-builder
    description: ''
    author: sumitpaul@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-20 08:42:01'
    datasets:
      inputs:
      - datasets/read_pdf
      outputs: []
    subgraphs:
    - subgraphs/BedrockSubgraph
    dependencies: {}
datasets:
  datasets/content_vectorized:
    name: content_vectorized
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:18:21'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Database
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:18:21'
  datasets/web_vectors:
    name: web_vectors
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:24:07'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Warehouse
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:24:07'
  datasets/web_scrape:
    name: web_scrape
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:36:38'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:36:38'
  datasets/bot_message:
    name: bot_message
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 13:52:46'
    mode: stream
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Database
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 13:52:46'
  datasets/get_queries_msk:
    name: get_queries_msk
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-04 15:50:54'
    mode: stream
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-04 15:50:54'
  datasets/opensearch-target:
    name: opensearch-target
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-10 15:26:00'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Warehouse
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-10 15:26:00'
  datasets/bot_msg_pinecone:
    name: bot_msg_pinecone
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-11 07:40:23'
    mode: stream
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Database
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-11 07:40:23'
  datasets/optum_pdf:
    name: optum_pdf
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-12 05:42:08'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-12 05:42:08'
  datasets/parse_docx:
    name: parse_docx
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-13 09:36:36'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-13 09:36:36'
  datasets/read_pdf:
    name: read_pdf
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-18 14:08:24'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-18 14:08:24'
  datasets/new_opensearch_sink:
    name: new_opensearch_sink
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-11-20 17:48:37'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Warehouse
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-11-20 17:48:37'
  datasets/Populate_Vector_DB:
    name: Populate_Vector_DB
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-12-11 13:08:09'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 3572
        datasetType: Warehouse
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-12-11 13:08:09'
templates: {}
jobs:
  jobs/test-optum-pipeline:
    name: test-optum-pipeline
    description: ''
    fabricUID: 42
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: sumitp
    scheduleCron: 0 3 4 * * ? *
    timeout: null
    alerting:
      emails: sumitpaul@prophecy.io
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/optum-pdf-data-vectorize
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-12-01 08:24:20'
    author: sumitpaul@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/SimplifiedBedrock:
      name: SimplifiedBedrock
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/SimplifiedBedrock.py
      dependencies: null
      createdAt: '2023-12-20 15:06:32'
  dependencies: null
functions:
  author: null
  createdAt: '2023-10-03 01:38:26'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs:
  subgraphs/BedrockSubgraph:
    name: BedrockSubgraph
    description: ''
    author: sumitpaul@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-12-20 13:06:21'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: pypi
  package: opensearch-py
  name: opensearchpy
  enabled: false
  id: 0d4Y6
  editable: true
- type: pypi
  package: boto3==1.28.62
  name: boto3
  enabled: false
  id: I7lDQ
  editable: true
- type: pypi
  package: pdf2image
  name: pdf2image
  enabled: false
  id: nRwR4
  editable: true
- type: pypi
  package: unstructured==0.7.4
  name: unstructured
  enabled: false
  id: pip5l
  editable: true
- type: pypi
  package: prophecy-spark-ai==0.1.11
  name: prophecy_spark_ai
  enabled: false
  id: Fql9s
  editable: false
projectDependencies:
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-12-05 15:13:03'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.7
    isDefault: true
    author: null
    createdAt: '2023-12-05 15:13:03'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-12-05 15:13:03'
  '16491':
    projectUID: 16491
    projectName: ProphecySparkMachineLearningPython
    repositoryPath: gitUri=https://github.com/prophecy-io/spark-machine-learning-python&subPath=/
    version: ProphecySparkMachineLearningPython/0.0.3
    isDefault: false
    author: null
    createdAt: '2023-12-11 14:36:30'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
